name: growapp
description: Grow api integration

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.3.0
  outline_material_icons: ^0.1.1
  google_fonts: ^1.1.0
  connectivity: ^0.4.9
  shared_preferences: ^0.5.8
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/